[workspace]
members = [
    "vello_bench_macros",
    "vello_bench_core",
    "vello_bench_cli",
    "vello_bench_wasm",
    "vello_bench_tauri",
]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "deny"
